clear;
clc;
%%
filepath='/glade/work/gwarner/HCR/hom_ug15_phi0_H005_large/output/';
phi=0;
tini=108000;
tend=160000;
Lz=4000;
dz=25;
ug=15;
T_scale=300;
g=9.81;
u_heights=dz/2:dz:Lz+(dz/2);
w_heights=0:dz:Lz;
dTdz_FT=0.01;
%%
theta=load([filepath,'theta_z_0',num2str(tini),'_0',num2str(tend),'.txt'])*T_scale;
dTdz=load([filepath,'dTdz_z_0',num2str(tini),'_0',num2str(tend),'.txt'])*(T_scale/Lz);
u=load([filepath,'u_z_0',num2str(tini),'_0',num2str(tend),'.txt'])*ug;
v=load([filepath,'v_z_0',num2str(tini),'_0',num2str(tend),'.txt'])*ug;
%%
ur=u.*cosd(phi)-v.*sind(phi);
vr=u.*sind(phi)+v.*cosd(phi);
%% ABL Depth
[max_val_w,max_ind_w]=max(dTdz);
zi_w=w_heights(max_ind_w);
%
dTdz_temp=(dTdz(2:end)+dTdz(1:end-1))/2;
[max_val_u,max_ind_u]=max(dTdz_temp);
zi_u=u_heights(max_ind_u);
%%
v_perp=-max(vr);
theta_bar=mean(theta(max_ind_u:end));
N=sqrt((g/theta_bar)*dTdz_FT);
wavelength_estimate_STEN=2*pi*abs(v_perp)/N;
%%
vel=sqrt((u(1:max_ind_u).^2)+(v(1:max_ind_u).^2));
vel_grad=(vel(3:end)-vel(1:end-2))/dz;
[val,ind]=min(abs(vel_grad));
vel_diff=15-vel(ind+1);
wavelength_estimate_MELF=2*pi*abs(vel_diff)/N;